# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20161007_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='zip',
            field=models.CharField(default='00000-0000', max_length=10),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='zip',
            field=models.CharField(default='00000-0000', max_length=10),
        ),
    ]
