# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('imageUrl', models.URLField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
